### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by krylovaaleksandra** [postalsys/imapflow#108]
**Describe the bug**
Using a http proxy sometimes an error occurs and the application crashes. 

**Error stack**

```
Error: This socket has been ended by the other party
at TLSSocket.writeAfterFIN [as write] (net.js:468:14)
at Imap.write (/node_modules/imapflow/lib/imap-flow.js:313:26)
at preCheck (/node_modules/imapflow/lib/commands/idle.js:34:32)
at Imap.connection.preCheck (/root/node_modules/imapflow/lib/commands/idle.js:62:17)
 at Imap.close (/node_modules/imapflow/lib/imap-flow.js:1262:18)
 at TLSSocket._socketEnd (/root/node_modules/imapflow/lib/imap-flow.js:545:22)
 at TLSSocket.emit (events.js:412:35)
 at endReadableNT (internal/streams/readable.js:1334:12)
 at processTicksAndRejections (internal/process/task_queues.js:82:21) {
 code: 'EPIPE'
 }

```

**Desktop:**
 - OS: Linux debian 10
 - Version imapflow@1.0.86

**Comment by krylovaaleksandra** [comment]
.catch doesnt work with this error :(

**Comment by andris9** [comment]
Proxy support is _as is_. It's not a priority, and it is not well-tested. If this is really an uncatchable error, then it would be great if you'd manage to find out what exactly the issue is and how to mitigate it.

**Comment by krylovaaleksandra** [comment]
at Imap.write (/node_modules/imapflow/lib/imap-flow.js:313:26)
I think that this method should be in `try {} catch {}`

**Comment by krylovaaleksandra** [comment]
this.writeSocket.write(chunk); should be in ` try {} catch {}`

**Comment by krylovaaleksandra** [comment]
Got it. 
class `PassThrough` support event` .on("error")`
so, to handle errors `this.writeSocket` should have `this.writeSocket.on('error') `handler
