### ISSUE TITLE
Error: TypeError: this.writeSocket.write is not a function

### ISSUE THREAD

**Issue by ressonix** [postalsys/imapflow#115]
**Describe the bug**
When using the `list()` function, the following error is thrown:

```
Error: TypeError: this.writeSocket.write is not a function
    at ImapFlow.write (/media/ressonix/NVME2/postal-service/node_modules/imapflow/lib/imap-flow.js:343:26)
    at ImapFlow.send (/media/ressonix/NVME2/postal-service/node_modules/imapflow/lib/imap-flow.js:388:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ImapFlow.trySend (/media/ressonix/NVME2/postal-service/node_modules/imapflow/lib/imap-flow.js:401:9)
```

**To Reproduce**
1. Attempt to use the example provided in the API reference docs after initiating the client and making the connection. See the following link for an example of this in action: https://github.com/ressonix/postal-service/blob/main/pages/api/migrate.ts

**Expected behavior**
Returns an array.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The remainder of the code linked in the "To Reproduce" section above works fine until I try to use the `list()` function.

**Comment by andris9** [comment]
You need to run the `connect()` method before you can run any other commands. In your code you try to run `list()` first.
