### ISSUE TITLE
Error thrown every time logout is called

### ISSUE THREAD

**Issue by shunkica** [postalsys/imapflow#161]
**Describe the bug**
Every time I call logout() on the client an error is thrown, even though all the actions have been completed successfully.

**To Reproduce**
connect, getMailboxLock, search, fetch, messageFlagsAdd, download, logout

** Versions **
Node v20
imapflow v1.0.147

**Additional context**
`2024-01-16 08:30:01.8305 udocit[640006]: {"level":20,"time":1705390201829,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","src":"s","msg":"12 OK Store completed (0.002 + 0.000 + 0.001 secs).","cid":"9soazgasnkgo67vfol5d"}
2024-01-16 08:30:01.8307 udocit[640006]: {"level":10,"time":1705390201829,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","msg":"Mailbox lock released","lockId":1,"path":"INBOX"}
2024-01-16 08:30:01.8308 udocit[640006]: {"level":20,"time":1705390201830,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","src":"s","msg":"13 LOGOUT","cid":"9soazgasnkgo67vfol5d"}
2024-01-16 08:30:01.8581 udocit[640006]: {"level":10,"time":1705390201857,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","msg":"Connection closed","cid":"9soazgasnkgo67vfol5d"}
2024-01-16 08:30:01.8689 udocit[640006]: {"level":40,"time":1705390201858,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","err":{"type":"Error","message":"Connection not available","stack":"Error: Connection not available\n    at ImapFlow.close (/app/node_modules/imapflow/lib/imap-flow.js:1437:32)\n    at TLSSocket._socketEnd (/app/node_modules/imapflow/lib/imap-flow.js:640:22)\n    at TLSSocket.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"cid":"9soazgasnkgo67vfol5d","msg":"Connection not available"}
2024-01-16 08:30:01.8691 udocit[640006]: {"level":20,"time":1705390201867,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","src":"s","msg":"* BYE Logging out","cid":"9soazgasnkgo67vfol5d"}
2024-01-16 08:30:01.8692 udocit[640006]: {"level":20,"time":1705390201868,"pid":1,"hostname":"09c2cba7f3ad","component":"imap-connection","cid":"9soazgasnkgo67vfol5d","src":"s","msg":"13 OK Logout completed (0.001 + 0.000 secs).","cid":"9soazgasnkgo67vfol5d"}
`

**Comment by andris9** [comment]
I can not reproduce it. Getting this error means that there is still something in the execution pipeline when the socket is closed. You should check what exactly it is [here](https://github.com/postalsys/imapflow/blob/6dd05a494b123eb50495883f6dd268d7d8acf022/lib/imap-flow.js#L1435)

**Comment by shunkica** [comment]
> I can not reproduce it. Getting this error means that there is still something in the execution pipeline when the socket is closed. You should check what exactly it is [here](https://github.com/postalsys/imapflow/blob/6dd05a494b123eb50495883f6dd268d7d8acf022/lib/imap-flow.js#L1435)

This is my test, and the error appears every time:

```
describe('imapflow', () => {
    let options: ImapFlowOptions = {
        host: keys.mailHost,
        port: keys.mailPort,
        secure: true,
        auth: {
            user: keys.mailUser,
            pass: keys.mailPass
        }
    }

    it('throws the error', async () => {
        const client = new ImapFlow(options);
        await client.connect();
        await client.logout();
        await new Promise(resolve => setTimeout(resolve, 1000));
    });
});
```

**Comment by andris9** [comment]
Which Node version are you using? I'm not able to reproduce this behaviour at all. Logout is always processed before TCP close.

**Comment by shunkica** [comment]
> Which Node version are you using? I'm not able to reproduce this behaviour at all. Logout is always processed before TCP close.

I am on node v20.10.0 on my machine, but the error also appears in the node:20-alpine container.

**Comment by shunkica** [comment]
I can confirm that v1.0.148 fixed the issue.

FWIW I created a account on a free emai lservice and tried to reproduce with v1.0.147 but couldn't.
Looks like the issue only happened with the Dovecot IMAP server.

**Comment by andris9** [comment]
It was a race condition where the TCP close event was processed before the server response message for LOGOUT, so it was not so much about the specific server but timing, which is unpredictable.

**Comment by gitschlonzo** [comment]
Hi andris,
could it be that recent changes reactivated this issue? Using imapflow >= 1.0.148 and < 1.0.154 works as described here. Any version >= 1.0.154 ist throwing an exception on logout again.
