### ISSUE TITLE
Getting "authentication failure" when trying to connect gmail with OAuth2

### ISSUE THREAD

**Issue by pkellner** [postalsys/imapflow#224]
I've followed your article on how to connect OAuth2 to ImapFlow and think I've got the flow working right because I do get prompted to authenticate as I expect, and the redirect does correctly show my gmail credentials. However, when I try and use the token to connect to ImapFlow again, I get the error ""authentication failure" .

Immediately after this code, my example constructs a call to google directly with the token and it does return the user info.  That is, this code works:

```JavaScript
  async function fetchUserInfo(accessToken: string) {
    const url = "https://www.googleapis.com/oauth2/v2/userinfo";
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });

    if (!response.ok) {
      throw new Error("Failed to fetch user info");
    }
    return response.json();
  }
```

I've got a very simple repro that causes the issue. Sorry for posting as an issue, because I'm sure it's something I'm doing wrong, but I've been crawling down hole after hold and not figured it out. also, I incorrectly posted the error and I've update this error accordingling.

Here is my simple repro:

```JavaScript
try {
      const oauth2Client = new google.auth.OAuth2(googleClientId, googleClientSecret, googleRedirectUri);
      const { tokens } = await oauth2Client.getToken(code);

      const access_token = tokens.access_token;
      //const id_token = tokens.id_token;

      const imapConfig = {
        host: "imap.gmail.com",
        port: 993,
        secure: true,
        auth: {
          user: "svcodecamp@gmail.com",
          accessToken: access_token as string,
        },
        debug: console.log,
      };

      const imapClient = new ImapFlow(imapConfig);
      const status = await imapClient.connect();
```

If this helps, this is my debug output:

```
{"level":30,"time":1728611045781,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"connection","msg":"Established secure TCP connection","cid":"01ncqi9bh2jdyjg6uc7h","secure":true,"host":"imap.gmail.com","servername":"imap.gmail.com","port":993,"address":"74.125.137.108","localAddress":"10.0.0.32","localPort":58028,"authorized":true,"algo":"TLS_AES_256_GCM_SHA384","version":"TLSv1.3"}
{"level":20,"time":1728611045876,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"* OK Gimap ready for requests from 67.63.80.185 bl16mb82572479oib","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611045877,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"1 CAPABILITY","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611045964,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611045966,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"1 OK Thats all she wrote! bl16mb82572479oib","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611045967,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"2 ID (\"name\" \"imapflow\" \"version\" \"1.0.164\" \"vendor\" \"Postal Systems\" \"support-url\" \"https://github.com/postalsys/imapflow/issues\")","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611046058,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"* ID (\"name\" \"GImap\" \"vendor\" \"Google, Inc.\" \"support-url\" \"http://support.google.com/mail\" \"remote-host\" \"67.63.80.185\" \"connection-token\" \"bl16mb82572479oib\")","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611046059,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"2 OK Success bl16mb82572479oib","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611046060,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"3 AUTHENTICATE OAUTHBEARER \"(* value hidden *)\"","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611046541,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"+ eyJzdGF0dXMiOiJpbnZhbGlkX3JlcXVlc3QiLCJzY29wZSI6Imh0dHBzOi8vbWFpbC5nb29nbGUuY29tLyJ9","cid":"01ncqi9bh2jdyjg6uc7h"}
{"level":20,"time":1728611046548,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"c","msg":"AQ==","comment":"Error response for OAUTHBEARER"}
{"level":20,"time":1728611046627,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","src":"s","msg":"3 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)","cid":"01ncqi9bh2jdyjg6uc7h"}
Error during OAuth callback: Error: Command failed
    at ImapFlow.reader (/Users/peterkellner/repos/gmail-to-icloud/process-mail-queue/node_modules/imapflow/lib/imap-flow.js:571:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: '3 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)',
  responseStatus: 'NO',
  responseText: 'Invalid credentials (Failure)',
  serverResponseCode: 'AUTHENTICATIONFAILED',
  authenticationFailed: true,
  oauthError: { status: 'invalid_request', scope: 'https://mail.google.com/' }
}
{"level":50,"time":1728611046628,"pid":63774,"hostname":"PKMBOOKPROM3-4.local","component":"imap-connection","cid":"01ncqi9bh2jdyjg6uc7h","err":{"type":"Error","message":"Command failed","stack":"Error: Command failed\n    at ImapFlow.reader (/Users/peterkellner/repos/gmail-to-icloud/process-mail-queue/node_modules/imapflow/lib/imap-flow.js:571:35)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","response":"3 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)","responseStatus":"NO","responseText":"Invalid credentials (Failure)","serverResponseCode":"AUTHENTICATIONFAILED","authenticationFailed":true,"oauthError":{"status":"invalid_request","scope":"https://mail.google.com/"}},"cid":"01ncqi9bh2jdyjg6uc7h","msg":"Command failed"}

```

**Comment by andris9** [comment]
This means that your access token is not correct. For example, it is not generated for the required OAuth2 scope (`https://mail.google.com/`)

**Comment by pkellner** [comment]
@andris9 , if the scope was wrong, wouldn't the fetchUserInfo fail when it is passed in the header as a bearer token? Are there any examples around using ImapFlow with gmail?

**Comment by andris9** [comment]
Userinfo endpoint and IMAP use different scopes. The fact that API command succeeds but IMAP authentication fails proves that your token is otherwise correct but is missing the `https://mail.google.com/` scope. When authenticating the user with Google OAuth, make sure that the IMAP scope is also requested.

**Comment by pkellner** [comment]
Thanks @andris9 . I totally understand. I'm guessing this is not an ImapFlow issue, but since I'm kind of circling the toilet, I'll post what I think is the obvious screen that shows I've got the scope set. Maybe there is something really stupid I'm doing? Sorry again for filling issues here. I know this is the wrong place.  

![image](https://github.com/user-attachments/assets/3a0a79c0-c020-450e-8ead-6ba7632743a6)

**Comment by andris9** [comment]
In general, if you can't solve it, I'd just advise you to use my paid product, [EmailEngine](https://emailengine.app/). It uses ImapFlow under the hood and handles everything related to OAuth2 itself. It supports access to Gmail accounts both over [IMAP and SMTP](https://docs.emailengine.app/setting-up-gmail-oauth2-for-imap-api/) and over the [Gmail API](https://docs.emailengine.app/setting-up-gmail-api-access/).

**Comment by pkellner** [comment]
Thanks @andris9 for the help. With your advice I was able to send the scope on the request. That is the part I had not understood earlier. EmailEngine looks awesome. If I can get the project I'm working on from the "hobby project" stage to actual production with a lot of customers, I will definitely look at using it.
