### ISSUE TITLE
How to search for emails by header?

### ISSUE THREAD

**Issue by bluepuma77** [postalsys/imapflow#77]
We would like to fetch all UIDs of emails with the `X-Save-Sent: 1` header. I tried various options, but it's not working for me. With an empty search I get all emails in INBOX, but with header search I always get zero, even though the header is definitely present. Using [Mailu server](https://github.com/mailu/mailu/) with Dovecot v2.3.15.

        let list = await client.search({ }, { uid: true }); // all
        let list = await client.search({ header: 'X-Save-Sent' }, { uid: true }); // 0
        let list = await client.search({ header: { 'X-Save-Sent': true } }, { uid: true }); // 0
        let list = await client.search({ header: { 'X-Save-Sent': '1' } }, { uid: true }); // 0

Maybe I just don't read the [SearchObject documentation](https://imapflow.com/global.html#SearchObject) correctly. Any hints?

My basic code:
```
// create IMAP object
const client = new ImapFlow(options);

// connect to IMAP server
await client.connect();

// open inbox
let mailbox = await client.mailboxOpen('INBOX');

// find messages
let list = await client.search({ header: { 'MIME-Version': '1.0' } }, { uid: true });

// close connection
await client.logout();
```
Debug log (enabled by default):
```
  {"src":"connection","msg":"Established secure TCP connection",,"secure":true,"host":"host.eu","servername":"host.eu","port":993,"address":"1.2.3.4","localAddress":"10.8.0.2","localPort":62971,"authorized":true,"algo":"TLS_AES_256_GCM_SHA384","version":"TLSv1.3"}
  {"src":"s","msg":"* OK IMAP4 ready",}
  {"src":"s","msg":"1 CAPABILITY",}
  {"src":"s","msg":"* CAPABILITY IMAP4 IMAP4rev1 UIDPLUS SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN",}
  {"src":"s","msg":"1 OK completed",}
  {"src":"s","msg":"2 ID (\"name\" \"imapflow\" \"version\" \"1.0.95\" \"vendor\" \"Postal Systems\" \"support-url\" \"https://github.com/postalsys/imapflow/issues\")",}
  {"src":"s","msg":"2 BAD invalid command",}
  {"err":{"type":"Error","message":"Command failed","stack":"Error: Command failed\n    at ImapFlow.reader (/x/node_modules/imapflow/lib/imap-flow.js:519:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","response":{"tag":"2","command":"BAD","attributes":[{"type":"TEXT","value":"invalid command"}]},"responseStatus":"BAD","responseText":"invalid command"},,"msg":"Command failed"}
  {"src":"s","msg":"3 LOGIN info@host.eu \"(* value hidden *)\"",}
  {"src":"s","msg":"3 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA] Logged in",}
  {"src":"auth","msg":"User authenticated",,"user":"info@host.eu"}
  {"src":"s","msg":"4 NAMESPACE",}
  {"src":"s","msg":"* NAMESPACE ((\"\" \".\")) NIL NIL",}
  {"src":"s","msg":"4 OK Namespace completed (0.001 + 0.000 secs).",}
  {"src":"s","msg":"5 ENABLE CONDSTORE",}
  {"src":"s","msg":"* ENABLED CONDSTORE",}
  {"src":"s","msg":"5 OK Enabled (0.001 + 0.000 secs).",}
  {"src":"s","msg":"6 LIST \"\" \"INBOX\"",}
  {"src":"s","msg":"* LIST (\\HasNoChildren) \".\" INBOX",}
  {"src":"s","msg":"6 OK List completed (0.001 + 0.000 secs).",}
  {"src":"s","msg":"7 LSUB \"\" \"INBOX\"",}
  {"src":"s","msg":"7 OK Lsub completed (0.001 + 0.000 secs).",}
  {"src":"s","msg":"8 SELECT INBOX",}
  {"src":"s","msg":"* FLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft Checked Notified)",}
  {"src":"s","msg":"* OK [PERMANENTFLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft Checked Notified \"\\\\*\")] Flags permitted.",}
  {"src":"s","msg":"* 731 EXISTS",}
  {"src":"s","msg":"* 0 RECENT",}
  {"src":"s","msg":"* OK [UNSEEN 1] First unseen.",}
  {"src":"s","msg":"* OK [UIDVALIDITY 1652449601] UIDs valid",}
  {"src":"s","msg":"* OK [UIDNEXT 1111] Predicted next UID",}
  {"src":"s","msg":"* OK [HIGHESTMODSEQ 2634] Highest",}
  {"src":"s","msg":"8 OK [READ-WRITE] Select completed (0.002 + 0.000 + 0.001 secs).",}
  {"src":"s","msg":"9 UID SEARCH HEADER MIME-VERSION 1.0",}
  {"src":"s","msg":"* SEARCH",}
  {"src":"s","msg":"9 OK Search completed (0.003 + 0.000 + 0.002 secs).",}
  {"src":"s","msg":"A LOGOUT",}
  {"src":"s","msg":"* BYE Logging out",}
  {"src":"s","msg":"A OK Logout completed (0.001 + 0.000 secs).",}
  {"msg":"Connection closed",}
```

**Comment by andris9** [comment]
IMAP search is heavily dependent on what the server actually supports or not. From the logs it seems that everything is correct, ImapFlow executes the SEARCH command as it is supposed to but the server does not return anything. I can only assume that the server has searching by header values disabled.

I tried the same command in another IMAP server and got the expected result:
```
9 UID SEARCH HEADER MIME-VERSION 1.0
* SEARCH 556 561 562 570 571 572 573 574 ....
```
