### ISSUE TITLE
Unable to do more than one request

### ISSUE THREAD

**Issue by erwanclx** [postalsys/imapflow#83]
Hi, i'm unable to do more than one requjest, my secund request sutck with this error : 

```
Error: Failed to receive greeting from server in required time
    at Timeout._onTimeout (c:\Users\erwan\Dev\PurpleMailAPI\node_modules\imapflow\lib\imap-flow.js:1193:31)
    at listOnTimeout (c:\Users\erwan\Dev\PurpleMailAPI\lib\internal\timers.js:559:17)
    at processTimers (node:internal/timers:502:7) {code: 'GREEETING_TIMEOUT', stack: 'Error: Failed to receive greeting from server…at processTimers (node:internal/timers:502:7)', message: 'Failed to receive greeting from server in required time'}
```

**Comment by zner0L** [comment]
I have the same problem. I use version 1.0.106 on node v14.18.2 and I test it against the ethreal.email test server. The connection is established with no problems the first time, but if I call `connect` a second time, even after I logged out, the connections times out on the greeting. If I create a new `ImapFlow` object, everything works as expected.

Here is a minimal broken example:
```js
const { ImapFlow } = require('imapflow');
const client = new ImapFlow({
    host: 'ethereal.email',
    port: 993,
    secure: true,
    auth: {
        user: 'garland.mcclure71@ethereal.email',
        pass: 'mW6e4wWWnEd3H4hT5B',
    },
});

const main = async () => {
    await client.connect();
    await client.logout();
    await client.connect(); // Error: Failed to receive greeting from server in required time
};

main();
```

**Comment by jprealini** [comment]
@zner0L Did you find a way to solve that? Or got any response from anywhere? Thanks

**Comment by jprealini** [comment]
@andris9 Did you have a chance to take a look at this issue?

**Comment by andris9** [comment]
One instance can be used for a single connection. Once the connection is lost, you can’t use that instance again.

**Comment by jprealini** [comment]
@andris9 @zner0L Hey.. I was able to make it work... the problem is caused by declaring the client "outside" of the main block (in my case, I am implementing this as a plugin for cypress, where what you have here as your "main" is my "getLastEmail" method)... 

You can see an example of the whole implementation here -- https://dev.to/jprealini/how-to-test-sent-and-received-emails-with-cypress-10-ethereal-and-nodemailer-5h25

```
const { ImapFlow } = require('imapflow');

const main = async () => {
    // Wait until client connects and authorizes
   let client = new ImapFlow({
    host: 'ethereal.email',
    port: 993,
    secure: true,
    auth: {
        user: 'garland.mcclure71@ethereal.email',
        pass: 'mW6e4wWWnEd3H4hT5B'
    }
});
    await client.connect();

    // Select and lock a mailbox. Throws if mailbox does not exist
    let lock = await client.getMailboxLock('INBOX');
    try {
        // fetch latest message source
        // client.mailbox includes information about currently selected mailbox
        // "exists" value is also the largest sequence number available in the mailbox
        let message = await client.fetchOne(client.mailbox.exists, { source: true });
        console.log(message.source.toString());

        // list subjects for all messages
        // uid value is always included in FETCH response, envelope strings are in unicode.
        for await (let message of client.fetch('1:*', { envelope: true })) {
            console.log(`${message.uid}: ${message.envelope.subject}`);
        }
    } finally {
        // Make sure lock is released, otherwise next `getMailboxLock()` never returns
        lock.release();
    }

    // log out and close connection
    await client.logout();
};

main().catch(err => console.error(err));
```

**Comment by m-naeem66622** [comment]
@jprealini Thanks Man
This one make my day.. almost waste 4-6 hours with just putting lines up and down testing the connections
