### ISSUE TITLE
idling failure not detected

### ISSUE THREAD

**Issue by phi1ipp** [postalsys/imapflow#98]
**Describe the bug**
I noticed that in our environment we see a periodical issue with idling. 

**To Reproduce**
When everything works fine we see the following on the server:
```
17:08:23.742 5 IMAP-026447([192.168.0.10]:46856) s-inp: 4BE IDLE
17:08:23.742 5 IMAP-026447([192.168.0.10]:46856) s-out: + idling\r\n
17:13:23.741 5 IMAP-026447([192.168.0.10]:46856) s-inp: DONE
```

But sometimes we see the following (subject to maybe network layer issues)
```
06:23:25.708 5 IMAP-026447([192.168.0.10]:46856) s-inp: 5FC IDLE
06:23:25.708 5 IMAP-026447([192.168.0.10]:46856) s-out: + idling\r\n
06:23:49.480 3 IMAP-026447([192.168.0.10]:46856) abort request
06:23:49.485 3 IMAP-026447([192.168.0.10]:46856) IDLE reading failed. Error Code=socket aborted
06:23:49.485 2 IMAP-026447([192.168.0.10]:46856) ACCOUNT(xxx@yyy.com) disconnected ([192.168.0.10]:46856)
06:23:49.485 4 IMAP-026447([192.168.0.10]:46856) TLS connection is closing
06:23:49.485 4 IMAP-026447([192.168.0.10]:46856) releasing stream
```

**Expected behavior**
I expect the library to be able to detect the fact that IDLE has not finished successfully and somehow notify/throw

**Comment by phi1ipp** [comment]
That's what I collected on the client side while imitating a break in the connection (containerized application)
```
bridge-bridge-1   | {"level":20,"time":1670088176191,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","src":"s","msg":"A IDLE","cid":"fqdszvjg2eubka6x5eb6"}
bridge-bridge-1   | {"level":20,"time":1670088176314,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","src":"s","msg":"+ idling","cid":"fqdszvjg2eubka6x5eb6"}
bridge-bridge-1   | {"level":20,"time":1670088176315,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","msg":"Initiated IDLE, waiting for server input","doneRequested":false}
...
bridge-bridge-1   | {"level":10,"time":1670088476335,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","msg":"Requesting IDLE break","lockId":0,"path":"INBOX","queued":1,"doneRequested":false,"canEnd":true,"doneSent":false}
bridge-bridge-1   | {"level":20,"time":1670088476336,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","src":"c","msg":"DONE","comment":"breaking IDLE","lockId":0,"path":"INBOX"}
bridge-bridge-1   | {"level":10,"time":1670088508345,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","msg":"Connection closed","cid":"fqdszvjg2eubka6x5eb6"}
bridge-bridge-1   | {"level":40,"time":1670088508345,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","err":{"type":"Error","message":"Connection not available","stack":"Error: Connection not available\n    at ImapFlow.close (/usr/src/app/node_modules/imapflow/lib/imap-flow.js:1358:32)\n    at TLSSocket._socketEnd (/usr/src/app/node_modules/imapflow/lib/imap-flow.js:600:22)\n    at TLSSocket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"cid":"fqdszvjg2eubka6x5eb6","msg":"Connection not available"}
bridge-bridge-1   | {"level":40,"time":1670088508348,"pid":1,"hostname":"0ad2a8a18603","component":"imap-connection","cid":"fqdszvjg2eubka6x5eb6","err":{"type":"Error","message":"Connection not available","stack":"Error: Connection not available\n    at ImapFlow.close (/usr/src/app/node_modules/imapflow/lib/imap-flow.js:1370:36)\n    at TLSSocket._socketEnd (/usr/src/app/node_modules/imapflow/lib/imap-flow.js:600:22)\n    at TLSSocket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"},"cid":"fqdszvjg2eubka6x5eb6","msg":"Connection not available"}
```

So it seems there is only a warning message dumped into the log but no outer throw.

**Comment by phi1ipp** [comment]
My bad, figured that `close` event is emitted in this case.

Thank you for your awesome work!
